### ISSUE TITLE
Allow us to pass in our own http.Client

### ISSUE THREAD

**Issue by chadgrant** [smartystreets/smartystreets-go-sdk#13]
It's extremely unusual for http type api's such as these to disable / hide the http.Client from the callers. We have our own tracing, retries, circuit breakers, debugging decorators and have no ability to pass in an http client. 

per google maps go sdk:

`maps.NewClient(maps.WithAPIKey(apikey), maps.WithHTTPClient(client))`

**Comment by mdwhatcott** [comment]
@chadgrant - Shots fired! We wouldn't want to be unusual, now, would we?! ;)

Check out the branch that I just pushed. Would that work?

**Comment by mdwhatcott** [comment]
@chadgrant - Did you see the commit I pushed a few days ago? I'd like to have your feedback before merging.

https://github.com/smartystreets/smartystreets-go-sdk/commit/139b829ad20ca5f4f80315f6b63b2d371471572f
