### ISSUE TITLE
batch loader offers no way to pass ctx to http clients

### ISSUE THREAD

**Issue by trashhalo** [smartystreets/smartystreets-go-sdk#15]
our spans for smartystreets are missing http calls because send batch doesnt take a context. Would be nice if possible to add that as an option.

**Comment by DuncanBeutler** [comment]
We are working on implementing this currently. Thank you for raising this
issue!

**Comment by DuncanBeutler** [comment]
WithContext option is now available for all clients. Examples have been updated to reflect the new method.
Let us know if there are any further issues!

**Comment by mdwhatcott** [comment]
👍
