### ISSUE TITLE
Zip code lookup example can be much clearer

### ISSUE THREAD

**Issue by seenickcode** [smartystreets/smartystreets-go-sdk#7]
Hello there, thank you for writing this example.  

I think the zip code example is quite confusing:  https://github.com/smartystreets/smartystreets-go-sdk/blob/master/examples/us-zipcode-api/main.go

The example basically fills up the max batch size with a single zip code. 

What would be far less confusing (I had to read through the source code on what was indeed happening) is to simply add 3 unique zip code lookups to the batch.  There's no reason to demo in a simple example the fact that there is a max batch size, I think the user will find that out in extreme cases as probably 90% of the cases is a simple, single zip code lookup.

Please do not take my feedback as an offense or insult, I simply want to give my opinion as an end user.  

Thank you!

**Comment by mdwhatcott** [comment]
Thanks for the feedback! Feel free to improve the example and submit a PR.
